export default {
  AUTHENTICATION: 'authentication',
  SAVE_USER: 'saveUser',
  IS_LOADING: 'isLoading',
  CELEBRATION_LIST: 'celebrationList',
  SUBSCRIBE_CELEBRATION: 'subscribeCelebration',
  ADD_EVENTS: 'addEvents',
  UPDATE_ADDRESS: 'updateAddress',
  ALL_USERS: 'allUsers',
  HAS_MORE: 'hasMore',
  SAVE_CARDS: 'saveCards',
  SAVE_NOTIFICATION: 'listNotification',
  SAVE_NETWORK_USERS: 'saveNetworkUsers',
  TAB_STATE: 'tabState',
  INITIATE_ONBOARDING: 'initiateOnboarding',
  INITIATE_USERS: 'initiateUsers',
  INITIATE_NOTIFICATION: 'initiateNotification',
  INITIATE_GOOGLE_SEARCH: 'initiateGoogleSearch',
  INITIATE_NETWORK: 'initiateNetwork',
  INITIATE_COMMON: 'initiateCommon',
  INITIATE_EVENT: 'initiateEvent',
  SAVE_MONTHLY_EVENTS: 'saveMonthlyEvents',
  SELECT_MONTH: 'selectMonth',
  TOGGLE_NOTIFICATION_MODAL: 'toggleNotificationModal',
  SAVE_STATES_LIST: 'saveStateList',
  SAVE_GOOGLE_SEARCH_RESULTS: 'saveGoogleSearchResults',
};
